apiVersion: v1
kind: Pod
metadata:
  name: jenkins-slave
  namespace: jenkins
  labels:
    jenkins-label: POD_LABEL
spec:
  hostAliases:
  - ip: "10.3.1.10"
    hostnames:
    - "s3.ubuntu.home"
  containers:
    - name: jnlp
      image: registry.ubuntu.home/alpine/jenkins/inbound-agent/3283.v92c105e0f819-8-alpine-jdk21:latest
      imagePullPolicy: Always
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 1
          memory: 1Gi
      securityContext:
          runAsUser: 1000
      stdin: true
      tty: true
      volumeMounts:
      - name: workspace-volume
        mountPath: /home/jenkins/agent
    - name: kaniko
      image:  registry.ubuntu.home/gcr.io/kaniko-project/executor:v1.24.0.debug
      imagePullPolicy: Always
      command:
        - /busybox/cat
      resources:
        limits:
          cpu: 400m
          memory: 800Mi
        requests:
          cpu: 400m
          memory: 800Mi
      stdin: true
      tty: true
      volumeMounts:
        - name: workspace-volume
          mountPath: /home/jenkins/agent
        - name: dockerconfigjson
          mountPath: /kaniko/.docker/config.json
          readOnly: true
          subPath: config.json
      workspace: /home/jenkins/agent
  imagePullSecrets:
    - name: regcred
  volumes:
    - name: workspace-volume
      emptyDir: {}
    - name: dockerconfigjson
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
